import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/shared/navbar";
import Footer from "../components/shared/footer";
import Hero from "../components/home/hero";
import Intro from "../components/home/intro";
import TrustedBySection from "../components/home/companies";
import WhyUs from "../components/home/whyUs";
import Map from "../components/home/map";
import GetTouch from "../components/home/getTouch";
import ContactUs from "../components/home/contactUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Built</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Intro />
      <TrustedBySection />
      <WhyUs />
      <Map />
      <GetTouch />
      <ContactUs />
      <Footer />
    </div>
  );
}
